name: Sync to S3
on:
  push:
   branches:
       -main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    -name: checkout Respiratory
    users: actions/checkout@v3

   -name: Configure AWS Credentials
   uses: aws-actions/configure-aws-credentials@v2
   with:
     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY}}
     aws-secret-key-id: ${{ secrets.AWS_SECRET_KEY}}
     aws-region: eu-north-1

   -name: Sync to  S3
    run: aws s3 sync . s3://pavithtask

    
